import type { Metadata } from "next";
import classNames from "classnames";
import Image from "next/image";
import "./globals.scss";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface INavBar {
	selected: boolean;
	icon: string;
	title: string;
}

const navBar: INavBar[] = [
	{ selected: false, icon: "home", title: "Dashboard" },
	{ selected: false, icon: "transfer", title: "Transactions" },
	{ selected: false, icon: "user", title: "Accounts" },
	{ selected: false, icon: "economic", title: "Investments" },
	{ selected: false, icon: "credit", title: "Credit Cards" },
	{ selected: false, icon: "loan", title: "Loans" },
	{ selected: false, icon: "service", title: "Services" },
	{ selected: false, icon: "econometrics", title: "My Privilege" },
	{ selected: true, icon: "setting_1", title: "Setting" },
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body>
				<div className="sidebar">
					<div className="logo">
						<Image src="/img/logo.png" width={183} height={36} alt="Logo" />
					</div>
					<ul>
						{navBar.map((item) => (
							<li
								key={item.title}
								className={classNames(item.selected ? "selected" : "")}
							>
								<Image
									src={"/img/" + item.icon + ".png"}
									width={25}
									height={25}
									alt="Logo"
								/>
								<span>{item.title}</span>
							</li>
						))}
					</ul>
				</div>
				<div className="main">
					<div className="nav">
						<Image
							className="menu-mobile"
							src="/img/burger.png"
							alt="menu"
							width={18}
							height={14}
						/>
						<h2 className="title">
							{navBar.find((item) => item.selected)?.title}
						</h2>
						<Image
							className="profile-mobile"
							src="/img/profile.png"
							alt="profile"
							width={35}
							height={35}
						/>
						<div className="profile-block">
							<div className="item search">
								<Image
									src="/img/search.png"
									width={20}
									height={20}
									alt="search"
								/>
								<input type="text" placeholder="Search for something" />
							</div>
							<div className="item">
								<Image
									src="/img/settings.png"
									alt="setting"
									width={25}
									height={25}
								/>
							</div>
							<div className="item">
								<Image
									src="/img/notification.png"
									alt="notification"
									width={25}
									height={25}
								/>
							</div>
							<div className="item profile">
								<Image
									src="/img/profile.png"
									alt="notification"
									width={50}
									height={50}
								/>
							</div>
						</div>
					</div>
					<main>
						<div className="page">{children}</div>
					</main>
				</div>
			</body>
		</html>
	);
}
